const tap = require('tap')
const cc = require('./App')
tap.throws(() => cc(), new Error('Please enter a vaild message'))
tap.throws(() => cc(''), new Error('Please enter a vaild message'))
tap.throws(() => cc(1), new Error('Please enter a vaild message'))
tap.equal(cc('yolo'), false)
tap.equal(cc('feat: dwedwed'), true)
tap.equal(cc('4040: dwedwe4040'), false)
tap.equal(cc('build(lol): dwedwe4040'), true)
tap.equal(cc('4040: dwedwe4040'), false)
tap.equal(cc('4040: dwedwe4040', ['4040']), true)
tap.equal(cc('4040: dwedwe4040', 1), false)
tap.equal(cc('4040: dwedwe4040', []), false)
